<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16304" started-at="2015-11-01T07:53:52Z" finished-at="2015-11-01T07:54:08Z">
    <groups>
      <group name="regression">
        <method signature="Scenario_Login.testValid_Login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_Component.Scenario_Login@7f560810]" name="testValid_Login" class="Scenario_Component.Scenario_Login"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="Scenario_Login.testLogin(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_Component.Scenario_Login@7f560810]" name="testLogin" class="Scenario_Component.Scenario_Login"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="16304" started-at="2015-11-01T07:53:52Z" finished-at="2015-11-01T07:54:08Z">
      <class name="Scenario_Component.Scenario_Login">
        <test-method status="FAIL" signature="testValid_Login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_Component.Scenario_Login@7f560810]" name="testValid_Login" duration-ms="14805" started-at="2015-11-01T13:23:54Z" data-provider="dp_ValidLogin" finished-at="2015-11-01T13:24:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GB_07]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[qtpworld2005@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[learn123]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[qtpworld2005 g]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Failed as Expected user was  qtpworld2005 g Actual Result is  Qtpworld2005 g]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Failed as Expected user was  qtpworld2005 g Actual Result is  Qtpworld2005 g
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at Scenario_Component.Scenario_Login.testValid_Login(Scenario_Login.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValid_Login -->
      </class> <!-- Scenario_Component.Scenario_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
